### ISSUE TITLE
SNPoseEstimation: 模型未初始化完成

### ISSUE THREAD

**Issue by mczha** [leftatrium2/AIDemo#2]
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
    Node number 33 (TfLiteGpuDelegateV2) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
        at com.sina.aidemo.posenet.PoseNetFloat075.estimateSinglePose(PoseNetFloat075.java:132)
        at com.sina.aidemo.posenet.PoseNetManager.estimate(PoseNetManager.java:55)
        at com.sina.aidemo.app.PoseActivity.classifyFrame(PoseActivity.java:115)
        at com.sina.aidemo.app.PoseActivity.access$100(PoseActivity.java:26)
        at com.sina.aidemo.app.PoseActivity$1.run(PoseActivity.java:37)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
采用的是一体机，是不是一定要OPenGL的支持

**Comment by leftatrium2** [comment]
你的机器的GPU不支持TFLite，可以试试：
public class AIConstants {
    public static final String TAG = "SNPoseEstimation";
    public static final boolean isDebug = true;

    public static int getDevice() {
        return 0;
    }

将getDevice中的返回值改为0，就是使用CPU方式，但速度可能会有影响
